<a href="https://colab.research.google.com/github/BryanHinostroza/tarea09-bh/blob/develop/TAREA_9_HINOSTROZA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a.	Realice el cálculo de la convolución para una imagen con la distribución de pixeles mostrada

In [1]:
import numpy as np
from scipy.signal import convolve2d
imagen = np.array([[8,6,4,1,9,8], [9,6,9,3,3,9], [5,1,9,8,5,5], [2,2,5,3,5,2], [6,5,5,2,0,6], [0,6,4,8,3,0]])
kernel = np.array([[1,2,-2], [0,1,1], [-1,-1,2]])
resultado = convolve2d(imagen, kernel, mode='valid')
print(resultado)

[[ 22  46  13 -10]
 [ 14  19  30  13]
 [  7  -6   7  16]
 [ 24  10  20  -9]]


In [2]:
import numpy as np

# Matriz de imagen (6x6)
imagen = np.array([
    [8, 6, 4, 1, 9, 8],
    [9, 6, 9, 3, 3, 9],
    [5, 1, 9, 8, 5, 5],
    [2, 2, 5, 3, 5, 2],
    [6, 5, 5, 2, 0, 6],
    [0, 6, 4, 8, 3, 0]
])

# Kernel (3x3)
kernel = np.array([
    [1, 2, -2],
    [0, 1, 1],
    [-1, -1, 2]
])

# Tamaño de la salida
output_shape = (imagen.shape[0] - kernel.shape[0] + 1,
                imagen.shape[1] - kernel.shape[1] + 1)

# Crear matriz de salida
output = np.zeros(output_shape, dtype=int)

# Convolución sin padding y con stride = 1
for i in range(output.shape[0]):
    for j in range(output.shape[1]):
        region = imagen[i:i+3, j:j+3]
        output[i, j] = np.sum(region * kernel)

# Mostrar resultado
print("Resultado de la convolución:")
print(output)


Resultado de la convolución:
[[ 39  30 -13  12]
 [ 19  34  24  -3]
 [ -5   5  16  25]
 [  8  19  -3   4]]


b.	Tomando como referencia las mismas tablas, realice un padding para la imagen.

In [3]:
import numpy as np

# Imagen original (6x6)
imagen = np.array([
    [8, 6, 4, 1, 9, 8],
    [9, 6, 9, 3, 3, 9],
    [5, 1, 9, 8, 5, 5],
    [2, 2, 5, 3, 5, 2],
    [6, 5, 5, 2, 0, 6],
    [0, 6, 4, 8, 3, 0]
])

# Kernel (3x3)
kernel = np.array([
    [1, 2, -2],
    [0, 1, 1],
    [-1, -1, 2]
])

# Aplicar padding de 1 alrededor de la imagen
imagen_padded = np.pad(imagen, pad_width=1, mode='constant', constant_values=0)

# Tamaño de la nueva salida
output_shape = (imagen_padded.shape[0] - kernel.shape[0] + 1,
                imagen_padded.shape[1] - kernel.shape[1] + 1)

# Crear matriz de salida
output = np.zeros(output_shape, dtype=int)

# Convolución con imagen con padding
for i in range(output.shape[0]):
    for j in range(output.shape[1]):
        region = imagen_padded[i:i+3, j:j+3]
        output[i, j] = np.sum(region * kernel)

# Mostrar resultados
print("Imagen con padding (8x8):")
print(imagen_padded)
print("\nResultado de la convolución con padding:")
print(output)


Imagen con padding (8x8):
[[0 0 0 0 0 0 0 0]
 [0 8 6 4 1 9 8 0]
 [0 9 6 9 3 3 9 0]
 [0 5 1 9 8 5 5 0]
 [0 2 2 5 3 5 2 0]
 [0 6 5 5 2 0 6 0]
 [0 0 6 4 8 3 0 0]
 [0 0 0 0 0 0 0 0]]

Resultado de la convolución con padding:
[[ 17  13  -4   4  29  -4]
 [ 16  39  30 -13  12  24]
 [ 14  19  34  24  -3  19]
 [ 16  -5   5  16  25  11]
 [ 23   8  19  -3   4  12]
 [  8  16  23  20  -7  12]]


c.	¿Qué resultado se obtendría para la imagen cuando se aplica un pooling con un kernel de 2×2?

In [4]:
import numpy as np

# Imagen original (6x6)
imagen = np.array([
    [8, 6, 4, 1, 9, 8],
    [9, 6, 9, 3, 3, 9],
    [5, 1, 9, 8, 5, 5],
    [2, 2, 5, 3, 5, 2],
    [6, 5, 5, 2, 0, 6],
    [0, 6, 4, 8, 3, 0]
])

# Dimensiones de la salida para kernel 2x2 y stride 2
output_shape = (imagen.shape[0] // 2, imagen.shape[1] // 2)
output = np.zeros(output_shape, dtype=int)

# Aplicar Max Pooling
for i in range(0, imagen.shape[0], 2):
    for j in range(0, imagen.shape[1], 2):
        region = imagen[i:i+2, j:j+2]
        output[i//2, j//2] = np.max(region)

# Mostrar resultado
print("Resultado del Max Pooling 2x2 con stride 2:")
print(output)


Resultado del Max Pooling 2x2 con stride 2:
[[9 9 9]
 [5 9 5]
 [6 8 6]]
